---
# tasks file for create_user
- name: Creating Service Account Group
  group:
          name: "{{ service_account_name }}"
          gid: "{{ service_account_groupname_gid }}"
          state: present

- name: Creating Owner Group
  group:
          name: "{{ owner_groupname }}"
          state: present

- name: Creating User
  user: 
          name: "{{ owner_username }}"
          groups: 
                  - "{{ service_account_name }}"
                  - "{{ owner_groupname }}"
          append: yes
          uid: "{{ service_account_username_uid }}"
          home: "{{ owner_username_home }}"
          shell: "{{ owner_username_shell }}"
          password: "{{ owner_passwd }}"
        #   password: "{{ owner_passwd | password_hash('sha512') }}"


